# SPDX-FileCopyrightText: 2020 The HedgeDoc developers (see AUTHORS file)
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install structor
        run:  "curl -sfL https://raw.githubusercontent.com/traefik/structor/master/godownloader.sh | bash -s -- -b ."
      - name: Add dummy requirements.txt
        run: cp mkdocs.requirements.txt requirements.txt
      - name: Run Structor
        run:  ./structor -o hedgedoc -r hedgedoc --dockerfile-url="https://raw.githubusercontent.com/hedgedoc/docs.hedgedoc.org/main/docs.Dockerfile" --menu.js-file="https://github.com/hedgedoc/docs.hedgedoc.org/blob/main/version-menu.js.gotmpl" --exp-branch=master
      - name: Deploy to GitHub Pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
